
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 05 16:32:16 CEST 2012
//----------------------------------------------------

package thingmlparser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INT_LITERAL = 11;
  public static final int LPAR = 8;
  public static final int EOF = 0;
  public static final int ID = 12;
  public static final int RBRACK = 7;
  public static final int TRANS = 10;
  public static final int error = 1;
  public static final int STATE = 3;
  public static final int RPAR = 9;
  public static final int LBRACK = 6;
  public static final int STATEMACHINE = 2;
  public static final int INIT = 4;
  public static final int FINAL = 5;
}

